apiVersion: apps/v1
kind: Deployment
metadata:
  name: session17-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session17-app
  template:
    metadata:
      labels:
        app: session17-app
    spec:
      containers:
        - name: app
          image: session17-devsecops:local
          imagePullPolicy: IfNotPresent
